
image: golang:latest

#services:
#- docker:dind



before_script:
- apk add --update make wget unzip protoc
- wget https://github.com/google/protobuf/releases/download/v3.5.0/protoc-3.5.0-linux-x86_64.zip
- unzip protoc-3.5.0-linux-x86_64.zip
- ls protoc-3.5.0-linux-x86_64
- go version

test:
  script:
  - echo okay
