
version: "3"

services:
  kafka:
    image: spotify/kafka
    ports:
      - "2181:2181"
      - "9092:9092"
  loqsmith:
    image: gitlab.qntfy.com:5003/quark/loqsmith:v3.3.2-sandbox
    ports:
      - "50051:50051"
      - "50050:50050"
    environment:
      - RPC_PORT=50051
      - REST_PORT=50050
  master:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
      args:
        FINCH_TYPE: master
        GO_BUILD_OPTIONS: -ldflags "-s" -a -installsuffix cgo
    volumes:
      - .:/app
    links:
      - loqsmith
    command: [
      "./wait-for-it.sh", "loqsmith:50051", "-s", "-t", "0", "--",
      "sh", "-c", "./master",
    ]
    ports:
      - "8080:8080"
      - "9190:9190"
      - "9191:9191"
    environment:
      - FINCH_DEBUG=true
      - FINCH_VERBOSE=true
      - FINCH_REST_PORT=8080
      - FINCH_MASTER_PORT=9190
      - FINCH_COLLECTOR_PORT=9191
      - FINCH_LOQSMITH_URI=loqsmith:50051
      - FINCH_LOQSMITH_HOST_APP=2
      - FINCH_AUDIT_WORKER_FREQUENCY=60
      - FINCH_REBALANCE_FREQUENCY=60
      - FINCH_EVICT_WORKERS_AFTER=120
  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
      args:
        FINCH_TYPE: worker
        GO_BUILD_OPTIONS: -ldflags "-s" -a -installsuffix cgo
    volumes:
      - .:/app
    links:
      - kafka
      - master
    command: [
      "./wait-for-it.sh", "master:9190", "-s", "-t", "0", "--",
      "sh", "-c", "./worker",
    ]
    environment:
      - FINCH_DEBUG=true
      - FINCH_VERBOSE=true
      - FINCH_MASTER_URI=master:9190
      - FINCH_KAFKA_BROKERS=kafka:9092
      - FINCH_KAFKA_TOPIC=finch.out
      - FINCH_TELEMETRY_FREQUENCY=30