
version: "3"

services:
    upstream1:
        image: abiosoft/caddy
        volumes:
            - ./mnt/upstream1/etc:/etc
            - ./mnt/upstream1/static:/static
        ports:
            - "8888:80"
        environment:
            - FOO=BAZ

