[run]
init_cmds = [
	["go", "install"],
	["go", "build"],
	["./co-chair"]
]									# Commands run in start
watch_all = true					# Watch all sub-directories
watch_dirs = ["$WORKDIR/ui/src"]						# Directories to watch
watch_exts = [".ts", ".tsx", ".html", ".css"]				# Extensions to watch
ignore = [".git", "node_modules"] 	# Directories to exclude from watching
ignore_files = []					# Regexps for ignoring specific notifies
build_delay = 1500					# Minimal interval to Trigger build event
interrupt_timout = 15				# Time to wait until force kill
graceful_kill = false				# Wait for exit and before directly kill
cmds = [
	["tsc"],
	["rm", "-rf", "../frontend/static"],
	["cp", "-r", "build/dist", "../frontend/static"]
]

[sync]
listen_addr = ":5050"
remote_addr = ":5050"
